### ISSUE TITLE
SparkJob for multiple config

### ISSUE THREAD

**Issue by Mikulasi** [godatadriven/scala-spark-application#1]
Hi Tim, i really like your solution. Great job. But can i ask you something about using SparkJob for multiple config? I faced with the case when for each spark job i have different config and for that i created separate case class and parser class. Is there an option to make SparkJob generic given multiple configs for each job? Thanks in advance

**Comment by timvancann** [comment]
Hi,

I’m glad you liked it!

To answer your question: “it is scala so anything’s possible!”. I’ve actually done this at clients as well, it is a very normal thing to have more than one config parser. I’ve prepared a solution for you to give you a bit of inspiration. 
Have a look at the branch generic-sparkjob where I’ve modified SparkJob.scala, UsageConfig.scala and WordCount.scala. Here’s direct link to the changes: https://github.com/godatadriven/scala-spark-application/tree/generic-sparkjob/src/main/scala/thw/vancann <https://github.com/godatadriven/scala-spark-application/tree/generic-sparkjob/src/main/scala/thw/vancann>

Good luck!

- Tim

**Comment by Mikulasi** [comment]
Thanks a lot
